steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deploy/docker/api/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/predictions-api:${_TAG}
      - .

images:
  - gcr.io/$PROJECT_ID/predictions-api:${_TAG}

substitutions:
  _TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY
